### ISSUE TITLE
Crash after 2023-01-29T05:05:44.587Z and before 2023-01-29T05:06:10.706Z

### ISSUE THREAD

**Issue by kevinlul** [DawnbrandBots/bastion-bot#268]
```
/app/node_modules/http2-wrapper/source/agent.js:396
                                                        const error = new Error('Session closed without receiving a SETTINGS frame');
                                                                      ^
Error: Session closed without receiving a SETTINGS frame
    at ClientHttp2Session.<anonymous> (/app/node_modules/http2-wrapper/source/agent.js:396:22)
    at Object.onceWrapper (node:events:627:28)
    at ClientHttp2Session.emit (node:events:513:28)
    at emitClose (node:internal/http2/core:1086:8)
    at TLSSocket.<anonymous> (node:internal/http2/core:1113:7)
    at TLSSocket.emit (node:events:525:35)
    at node:net:320:12
    at TCP.done (node:_tls_wrap:588:7)
Emitted 'error' event on ClientRequest instance at:
    at ClientRequest.flushHeaders (/app/node_modules/http2-wrapper/source/client-request.js:363:10) {
  code: 'HTTP2WRAPPER_NOSETTINGS'
}
Node.js v18.13.0
```

**Comment by kevinlul** [comment]
As expected, this is a dependency of `got`. Apparently a beta version is being consumed: https://github.com/DawnbrandBots/bastion-bot/blob/master/yarn.lock#L3164-L3176

**Comment by kevinlul** [comment]
Current release: [2.2.0](https://www.npmjs.com/package/http2-wrapper/v/2.2.0) 💀

**Comment by kevinlul** [comment]
Issue filed: sindresorhus/got#2210

**Comment by kevinlul** [comment]
Possibly related, discovered from search:
- szmarczak/http2-wrapper#43
- szmarczak/http2-wrapper#69
