### ISSUE TITLE
/price errors: migrate to new API

### ISSUE THREAD

**Issue by kevinlul** [DawnbrandBots/bastion-bot#273]
```
TypeError: Cannot read properties of null (reading 'map')
    at PriceCommand.execute (/src/commands/price.ts:157:8)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task\_queues:96:5)
    at PriceCommand.run (/src/Command.ts:41:20)
    at InteractionListener.run (/src/events/interaction.ts:28:3)
```

**Comment by kevinlul** [comment]
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at PriceCommand.getPrice (/src/commands/price.ts:109:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PriceCommand.execute (/src/commands/price.ts:128:19)
    at PriceCommand.run (/src/Command.ts:41:20)
    at InteractionListener.run (/src/events/interaction.ts:32:5)
```

**Comment by kevinlul** [comment]
https://db.ygoprodeck.com/queries/getPrices.php?cardone=Nibiru%2C%20the%20Primal%20Being&vendor=tcgplayer

Empty response body declared as JSON

**Comment by kevinlul** [comment]
https://db.ygoprodeck.com/queries/getPrices.php?cardone=Dimensional%20Barrier&vendor=tcgplayer

Ditto

**Comment by kevinlul** [comment]
Forward path is actually to migrate to the new version of this API:

- https://ygoprodeck.com/api/card/getCardPrices.php?cardname=Time%20Wizard
- https://ygoprodeck.com/api/card/getCardPrices.php?cardname=Time%20Wizard&store=cardmarket
- https://ygoprodeck.com/api/card/getCardPrices.php?cardname=Time%20Wizard&store=tcgplayer
